#logging:
#  level:
#    root: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:dbunit_junit5_springboot2
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
#    hibernate:
#      ddl-auto: create-drop # default is create-drop because embedded database
    showSql: true
    databasePlatform: org.hibernate.dialect.H2Dialect
